services:
  subspace-api:
    build: ./
    image: ghcr.io/subtype-space/subspace-api:latest
    container_name: subspace-api
    restart: always
    ports:
      - 9595:9595
    env_file: .env
    networks:
      - proxy
      - api

networks:
  proxy:
    external: true
  api:
    external: true